# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

volumes:
  postgres-data-volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/manishgarg/software/postgres/data
      o: bind